### ISSUE TITLE
Installation on Ubuntu Linux

### ISSUE THREAD

**Issue by davidadamojr** [appium/ruby_console#50]
Is it possible to install appium_console on Ubuntu/Linux? I have tried to do this numerous times but always get the following error: 

```
~$ sudo gem install appium_console
Building native extensions.  This could take a while...
ERROR:  Error installing appium_console:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/1.9.1/gems/ffi-1.9.10/ext/ffi_c
/usr/bin/ruby1.9.1 -r ./siteconf20160116-575-1udezgu.rb extconf.rb
/usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from extconf.rb:4:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/1.9.1/extensions/x86_64-linux/1.9.1/ffi-1.9.10/gem_make.out
```
Is this something I am doing wrong or does appium_console only work in Mac OS X at the moment? If so, are there any plans for a Linux-compatible version?

**Comment by bootstraponline** [comment]
Use Ruby 2.2.3. It should work. 1.9 isn't supported.

**Comment by davidadamojr** [comment]
Awesome. That fixed it. Thanks for the quick response.
