### ISSUE TITLE
arc setup ios fails

### ISSUE THREAD

**Issue by angeliaw** [appium/ruby_console#57]
arc setup ios
WARN: Unresolved specs during Gem::Specification.reset:
      rubyzip (~> 1.0)
      json (~> 1.8)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/appium_console-2.0.1/lib/cli.rb:25:in `initialize': No such file or directory @ rb_sysopen - templates/appium.txt.erb (Errno::ENOENT)
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/appium_console-2.0.1/lib/cli.rb:25:in`new'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/appium_console-2.0.1/lib/cli.rb:25:in `ios'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor.rb:235:in`block in subcommand'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/appium_console-2.0.1/lib/cli.rb:80:in `<top (required)>'
    from /Users/angeliaw/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in`require'
    from /Users/angeliaw/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/gems/appium_console-2.0.1/bin/arc:3:in`<top (required)>'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/bin/arc:22:in `load'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/bin/arc:22:in`<main>'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
    from /Users/angeliaw/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in`<main>'

**Comment by angeliaw** [comment]
appium_console: v2.0.1
    appium_lib: v8.0.2
