### ISSUE TITLE
page command fails with appium-1.6.0beta1

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/ruby_console#58]
With appium 1.6.0 beta 1, there's preliminary support for XCUITest, since UI Automation is deprecated in Xcode 8.

Unfortunately, I can't seem to use page in arc when using this combination :(

To Reproduce:
1. sudo npm install -g appium@1.6.0-beta1
2. appium &
3. cd project/ios
4. arc
5. Wait for arc to launch
6. page

The exception is:

```
[debug] [XCUITest] Executing command 'execute'
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'sendCommand' of undefined
    at XCUITestDriver.callee$0$0$ (lib/commands/execute.js:19:37)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as execute] (lib/commands/execute.js:10:48)
    at lib/basedriver/driver.js:174:24
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

```
appium.txt:
[caps]
platformName = "iOS"
automationName = "XCUITest"
app = "~/appium/myApp.app"
platformVersion = "9.3"
deviceName = "iPad Retina"
fullReset = "true"
```

**Comment by bootstraponline** [comment]
I recommend using Pry directly for the XCUITest driver. The Appium Ruby project and related tools [are unmaintained](https://github.com/appium/ruby_lib/issues/337). As a result, they're not compatible with the new driver.

If you're a Sauce Labs customer, let them know Ruby support is important to you.

**Comment by VivaLosDoyers** [comment]
That is super depressing to hear.

**Comment by bootstraponline** [comment]
I'll leave this issue open just in case anything changes. I agree though, it's not an ideal situation.

**Comment by tejasv02** [comment]
Are there any other solutions similar to ruby console ?

**Comment by VivaLosDoyers** [comment]
Now that appium 1.6.0 is out, I'd really like to see something done about this

**Comment by momojah** [comment]
When writing tests I totally rely on ARC. Please maintain. What are our alternatives?

**Comment by VivaLosDoyers** [comment]
If you use the "source" command you can see the raw DOM. It's not a fun, but you can at least use it to find id names.

**Comment by alserik** [comment]
unfortunate! Pinging sauce!

**Comment by VivaLosDoyers** [comment]
Thanks! I tweeted them a couple of times about this, with no replies. :(

**Comment by alserik** [comment]
Looks like our voice has been heard on this, but will ultimately depend on resource availability to get this and other Ruby Tools up to speed for appium 1.6

**Comment by KazuCocoa** [comment]
`page` may be fixed in ruby_lib 9.0.0, I guess.

**Comment by VivaLosDoyers** [comment]
I'm happy to say this has been fixed. I'm not sure exactly when, but with Appium 1.6.3, Ruby users can use page again.

**Comment by KazuCocoa** [comment]
`page` command depends on `appium_lib`, and the library's `page` command has been fixed.
So, if users using latest appium_lib and latest Appium server can use `page`.

Anyway, thanks for closing the issue 👍
